<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>
<script type="text/javascript">
    $("#telefone, #celular").mask("(00) 0000-00000");
    $("#cpf").mask("000.000.000-00");
    $("#rg").mask("0.000.000");
    $("#cep").mask("00.000-000");
</script>

<title>Alterar dados</title>
<div class="container">
    <h3>Alterar dados</h3>
    <hr class="mt-3">
    <?php 
        if(isset($_SESSION['msg'])){
            echo $_SESSION['msg'];
            unset($_SESSION['msg']);
        }
    ?>
    <?php 
        foreach($this->dados as $valor){ ?>
    <div class="col-12">
        <div class="col-12">
            <form action="/execAlterarDados" method="POST" class="d-flex">
                <div class="col-1">
                    <label for="nome" class="form-label">Nome</label>
                </div>
                <div class="col-5">
                    <input type="hidden" value="NOME" name="campo">
                    <input type="text" name="alter" id="nome" value="<?= $valor->NOME; ?>"
                        class="form-control col-6 ml-3">
                </div>
                <div class="ml-3">
                    <button type="submit" class="btn btn-warning ml-2">Alterar</button>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="col-12">
        <div class="col-12">
            <form action="/execAlterarDados" method="POST" class="d-flex">
                <div class="col-1">
                    <label for="nome" class="form-label">E-mail</label>
                </div>
                <div class="col-5">
                    <input type="hidden" value="EMAIL" name="campo">
                    <input type="email" name="alter" id="email" value="<?= $valor->EMAIL; ?>"
                        class="form-control col-6 ml-3">
                </div>
                <div class="ml-3">
                    <button type="submit" class="btn btn-warning ml-2">Alterar</button>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="col-12">
        <div class="col-12">
            <form action="/execAlterarDados" method="POST" class="d-flex">
                <div class="col-1">
                    <label for="tel" class="form-label">Telefone</label>
                </div>
                <div class="col-5">
                    <input type="hidden" value="TELEFONE" name="campo">
                    <input type="tel" name="alter" id="telefone" value="<?= $valor->TELEFONE; ?>"
                        class="form-control col-6 ml-3">
                </div>
                <div class="ml-3">
                    <button type="submit" class="btn btn-warning ml-2">Alterar</button>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="col-12">
        <div class="col-12">
            <form action="/execAlterarDados" method="POST" class="d-flex">
                <div class="col-1">
                    <label for="rg" class="form-label mr-4">RG</label>
                </div>
                <div class="col-5">
                    <input type="hidden" value="RG" name="campo">
                    <input type="text" name="alter" id="rg" value="<?= $valor->RG; ?>" class="form-control col-6 ml-3">
                </div>
                <div class="ml-3">
                    <button type="submit" class="btn btn-warning ml-2">Alterar</button>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="col-12">
        <div class="col-12">
            <form action="/execAlterarDados" method="POST" class="d-flex">
                <div class="col-1">
                    <label for="rg" class="form-label mr-4">CEP</label>
                </div>
                <div class="col-5">
                    <input type="hidden" value="CEP" name="campo">
                    <input type="text" name="alter" id="cep" value="<?= $valor->CEP; ?>"
                        class="form-control col-6 ml-3">
                </div>
                <div class="ml-3">
                    <button type="submit" class="btn btn-warning ml-2">Alterar</button>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="col-12">
        <div class="col-12">
            <form action="/execAlterarDados" method="POST" class="d-flex">
                <div class="col-1">
                    <label for="endereco" class="form-label mr-4">Endereço</label>
                </div>
                <div class="col-5">
                    <input type="hidden" value="ENDERECO" name="campo">
                    <input type="text" name="alter" id="endereco" value="<?= $valor->ENDERECO; ?>"
                        class="form-control col-6 ml-3">
                </div>
                <div class="ml-3">
                    <button type="submit" class="btn btn-warning ml-2">Alterar</button>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="col-12">
        <div class="col-12">
            <form action="/execAlterarDados" method="POST" class="d-flex">
                <div class="col-1">
                    <label for="cidade" class="form-label mr-4">Cidade</label>
                </div>
                <div class="col-5">
                    <input type="hidden" value="CIDADE" name="campo">
                    <input type="text" name="alter" id="cidade" value="<?= $valor->CIDADE; ?>"
                        class="form-control col-6 ml-3">
                </div>
                <div class="ml-3">
                    <button type="submit" class="btn btn-warning ml-2">Alterar</button>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="col-12">
        <div class="col-12">
            <form action="/execAlterarDados" method="POST" class="d-flex">
                <div class="col-1">
                    <label for="numero" class="form-label mr-4">Número</label>
                </div>
                <div class="col-5">
                    <input type="hidden" value="NUM_CASA" name="campo">
                    <input type="text" name="alter" id="numero" value="<?= $valor->NUM_CASA; ?>"
                        class="form-control col-6 ml-3">
                </div>
                <div class="ml-3">
                    <button type="submit" class="btn btn-warning ml-2">Alterar</button>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="mt-5">
        <a href="/restrito" class="btn btn-outline-danger col-1">Voltar</a>
    </div>
    <?php   } ?>
</div>