<title>Meus dados</title>
<div class="container">
    <h3>Meus dados</h3>
    <hr class="mt-3">
    <?php
        foreach($this->dados as $valor){ ?>
            <div>
                <h6>Nome: <?= $valor->name; ?></h6>
            </div>
            <div>
                <h6>E-mail: <?= $valor->email; ?></h6>
            </div>
            <div>
                <h6>Telefone: <?= $valor->phone; ?></h6>
            </div>
            <div>
                <h6>CPF: <?= $valor->cpf; ?></h6>
            </div>
            <div>
                <h6>RG: <?= $valor->rg; ?></h6>
            </div>
            <div>
                <h6>CEP: <?= $valor->cep; ?></h6>
            </div>
            <div>
                <h6>Endereço: <?= $valor->address; ?></h6>
            </div>
            <div>
                <h6>Cidade: <?= $valor->city; ?></h6>
            </div>
            <div>
                <h6>UF: <?= $valor->uf; ?></h6>
            </div>
            <div>
                <h6>Número: <?= $valor->number_address; ?></h6>
            </div>
            <div class="mt-5">
                <a href="/restrito" class="btn btn-outline-danger col-1">Voltar</a>
            </div>
<?php   } ?>
</div>
