<h3>Atendimento</h3>
<hr/>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col">Mensagem</th>
    </tr>
  </thead>
  <tbody>
    <?php
        foreach($this->dados as $valor){?>
            <tr>
                <th scope="row"><?= $valor->id; ?></th>
                    <td><?= $valor->Nome; ?></td>
                    <td><?= $valor->Email; ?></td>
                    <td><?= $valor->Mensagem; ?></td>
                    <td>
                        <div>
                            <a class="btn btn-warning" href="/responderMensagem?id" role="button">responder</a>
                        </div>
                    </td>
                </th>
            </tr>
            
    <?php } ?>
  </tbody>
</table>
<div>
    <hr>
    <div class="d-flex justify-content-end">
        <a href="restritoadmin"><button id="voltar" type="button" class="btn btn-dark form-group mb-5">Voltar</button></a>
    </div>
    <div class="d-flex justify-content-end">
        <?php 
            echo $_SESSION['sNome'].", você está logado! [<a href='/logout'>Logout</a>]";
        ?>
    </div>
</div>