<?php 

  if(isset($_SESSION['msg'])){
    echo $_SESSION['msg'];
    unset($_SESSION['msg']);
  }

?>

<h3 class="d-flex justify-content-center">Produtos</h3>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Produto</th>
      <th scope="col">Preço</th>
      <th scope="col">Descrição</th>
      <th scope="col">Categoria</th>
      <th scope="col">Imagem</th>
    </tr>
  </thead>
  <tbody>
    <?php
        foreach($this->dados as $valor){?>
            <tr>
                <th scope="row"><?= $valor->id; ?></th>
                    <td><?= $valor->Nome; ?></td>
                    <td><?= $valor->Preco; ?></td>
                    <td><?= $valor->Descricao; ?></td>
                    <td><?= $valor->Categoria; ?></td>
                    <td>
                        <div>
                            <a class="btn btn-outline-dark" data-toggle="modal" data-target="#<?= $valor->id?>" href="" value="<?= $valor->id?>" role="button">ver imagem</a>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-warning" href="admAtualizarProduto?id=<?= $valor->id; ?>" role="button">Alterar</a>
                        <a class="btn btn-danger" href="admExcluirProduto?id=<?= $valor->id; ?>" role="button">Excluir</a>
                    </td>
                </th>
            </tr>
            <div class="modal fade" id="<?= $valor->id?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Imagem</h5>
                           <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <img src="">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Fechar</button>
                        </div>
                    </div>
                </div>
            </div>
    <?php } ?>
  </tbody>
</table>
<div>
    <hr>
    <div class="d-flex justify-content-end">
        <a href="restritoadmin"><button id="voltar" type="button" class="btn btn-dark form-group mb-5">Voltar</button></a>
    </div>
    <div class="d-flex justify-content-end">
        <?php 
            echo $_SESSION['sNome'].", você está logado! [<a href='/logout'>Logout</a>]";
        ?>
    </div>
</div>
