<title>Sobre</title>
<div class="container">
    <h3>Sobre</h3>
    <hr class="mt-3">
    <div>
        <h4>Feito com amor, carinho e a mão </h4><br>
    </div>
    <div>
        <p>
            A RB Aromas é um empreendimento familiar, focado na confecção de aromatizantes para ambientes. Trabalhamos
            com diferentes modelos, visando atender necessidades diversas.
        </p>
        <p>
            Irure ea amet minim duis aliquip minim veniam exercitation. Non officia exercitation fugiat cupidatat.
            Culpa laborum exercitation culpa non magna aliqua cillum nulla qui ut commodo aliquip nisi labore.
        </p>
        <p>
            Exercitation consectetur sit commodo duis. Ex reprehenderit duis velit ea elit enim amet ullamco
            eiusmod ea excepteur aliquip cillum ut. Magna enim reprehenderit tempor veniam minim nostrud.
            Aliqua elit Lorem officia ullamco elit exercitation. Exercitation adipisicing anim incididunt
            anim mollit.
        </p>
    </div>
</div>