<title>Carrinho</title>
<div class="container">
    <h3>Carrinho</h3>
    <hr>
    <?php
    if (isset($_SESSION['msg'])) {
        echo $_SESSION['msg'];
        unset($_SESSION['msg']);
    }
    ?>
    <ul class="list-group mb-3">
        <?php
        if (count($_SESSION['kart']) == 0) { ?>
            <div class="d-flex justify-content-center align-items-center" style="height: 300px;">
                <h1 class="text-muted d-flex" disabled>
                    Carrinho Vazio ;)
                </h1>
            </div>
            <?php } else {
            $qtd = 1;
            $i = 0;
            $total = 0;
            $count = count($this->dados);
            for ($i; $i < $count; $i++) {
                foreach ($this->dados[$i] as $valor) {
                    $id = $valor->id;
                    if (!isset($_SESSION['count'][$id])) {
                        $_SESSION['count'][$id] = 1;
                    }
                    $qtd = intval($_SESSION['count'][$id]);
                    $total = $total + ($valor->price) * $qtd;
                    if ($valor->stock < $qtd) {
                        $_SESSION['count'][$id] = $valor->stock;
                        $total = $total - ($valor->price);
                    }
            ?>

                    <li class="list-group-item py-3">
                        <div class="row g-3">
                            <div class="col-4 col-md-3 col-lg-2">
                                <a href="#">
                                    <img src="Img/Produtos/<?= $valor->image ?>" class="img-thumbnail">
                                </a>
                            </div>
                            <div class="col-8 col-md-9 col-lg-7 col-xl-7 text-left align-self-center">
                                <h4>
                                    <b>
                                        <a href="#" class="text-decoration-none text-danger">
                                            <?= $valor->name ?>
                                        </a>
                                    </b>
                                </h4>
                                <h4>
                                    <small><?= $valor->description ?></small>
                                </h4>
                            </div>
                            <div class="col-6 offset-6 col-sm-6 offset-sm-6 col-md-4 offset-md-8 col-lg-3 offset-lg-0  col-lx-2 align-self-center mt-3">
                                <div class="input-group">
                                    <form action="/carrinho" method="GET">
                                        <button type="submit" class="btn btn-outline-dark  border border-none">
                                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z" />
                                            </svg>
                                        </button>
                                        <input type="hidden" name="acao" value="contar1">
                                        <input type="hidden" name="id" value="<?= $valor->id ?>">
                                    </form>
                                    <input type="text" class="form-control text-center border border-none" name="qtd" value="<?= $_SESSION['count'][$id] ?>">
                                    <form action="/carrinho" method="GET">
                                        <button type="submit" class="btn btn-outline-dark border border-none">
                                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z" />
                                            </svg>
                                        </button>
                                        <input type="hidden" name="acao" value="contar2">
                                        <input type="hidden" name="id" value="<?= $valor->id ?>">
                                    </form>
                                    <form action="/carrinho" method="GET">
                                        <input type="hidden" name="id" value="<?= $valor->id ?>">
                                        <input type="hidden" value="del" name="acao">
                                        <button type="submit" class="btn border border-none btn-danger" action="<?= $qtd = $qtd + 1 ?>">
                                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                            </svg>
                                        </button>
                                    </form>
                                </div>
                                <div class="text-right mt-2">
                                    <small class="text-secondary">Estoque: <?= $valor->stock ?></small><br>
                                    <span class="text-dark">Preco: R$ <?= $valor->price ?></span>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php } ?>
            <?php } ?>
            <li class="list-group-item py-3">
                <div class="text-right">
                    <form action="/finalizar" method="GET">
                        <h4 class="text-dark mb-3">Valor total: R$ <?= $total ?></h4>
                        <a href="/produtos" class="btn btn-success">Continuar Comprando</a>
                        <button type="submit" class="btn btn-danger">Fechar Compra</button>
                        <input type="hidden" name="fim" value="finalizar">
                    </form>
                </div>
            </li>
        <?php } ?>
    </ul>
</div>

<?php
if (count($_SESSION['kart']) != 0) {
    $_SESSION['total'] = $total;
}
?>