<title>Administração</title>
<div class="container mt-5">
    <div class="row">
        <div class=" d-flex flex-wrap justify-content-center">
            <div class="text-center bg-light mr-3 mb-3">
                <a href="/cadastroproduto"><button class="btn btn-outline-dark">Cadastrar Produto</button></a>
            </div>
            <div class=" bg-light mr-3 mb-3">
                <a href="/listaprodutos" class="btn btn-outline-dark">Alterar Produto</a>
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center py-3 bg-light border">
        <?php
        echo $_SESSION['sNome'] . ", você está logado! [<a href='/logout'>Logout</a>]";
        ?>
    </div>
</div>