<title>Minha Página</title>
<div class="container">
    <h3>Minha Página</h3>
    <hr />
    <div class="">
        <a href="/meusDados" class="btn btn-outline-dark border-none col-3">Meus Dados</a>
    </div>
    <div class="mt-3 md-5">
        <a href="/alterarDados" class="btn btn-outline-dark border-none col-3">Alterar Dados</a>
    </div>
    <div class="mt-3">
        <?php 
            echo $_SESSION['sNome']." você está logado! [<a href='/logout'>Logout</a>]";
        ?>
    </div>
</div>