<!doctype html>
<html lang="pt-br">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="Css/index.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">

    <link rel="apple-touch-icon" sizes="180x180" href="/Img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/Img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/Img/favicon/favicon-16x16.png">
    <link rel="manifest" href="/Img/favicon/site.webmanifest">
    <link rel="mask-icon" href="/Img/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="/Img/favicon/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="/Img/favicon/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark border-bottom bg-dark shadow-sm mb-3">
        <div class="container">
            <a class="navbar-brand" href="/">Inicio</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a href="/produtos" class="nav-link text-white">Produtos</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link text-white">Customizar</a>
                    </li>
                </ul>
                <?php
                if (isset($_SESSION['sId'])) { ?>
                    <div class="aling-self-end">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a href="/pedidos" class="nav-link text-white">Pedidos</a>
                            </li>
                            <li class="nav-item">
                                <a href="/restrito" class="nav-link text-white">Conta</a>
                            </li>
                            <li class="nav-item pl-2">
                                <a href="/carrinho">
                                    <svg width="24px" height="24px" viewBox="0 0 16 16" class="bi bi-cart3" fill="white" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                                    </svg>
                                </a>
                            </li>
                            <ul>
                    </div>
                <?php  } else { ?>
                    <div class="aling-self-end">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a href="/cadastro" class="nav-link text-white">Quero Me Cadastrar</a>
                            </li>
                            <li class="nav-item">
                                <a href="/autenticar" class="nav-link text-white">Entrar</a>
                            </li>
                            <li class="nav-item pl-2">
                                <a href="/carrinho">
                                    <svg width="24px" height="24px" viewBox="0 0 16 16" class="bi bi-cart3" fill="white" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                                    </svg>
                                </a>
                            </li>
                            <ul>
                    </div>
                <?php   } ?>
            </div>
        </div>
    </nav>
    <main>
        <?= $this->content(); ?>
        <div style="height: 273px;" class="d-block d-md-none"></div>
        <div style="height: 153px;" class="d-none d-md-block d-lg-none"></div>
        <div style="height: 129px;" class="d-none d-lg-block"></div>
    </main>

    <footer class="border-top fixed-bottom mt-3 text-muted bg-dark">
        <div class="container">
            <div class="row py-3">
                <div class="col-12 col-md-4 text-center text-md-left">

                </div>
                <div class="col-12 col-md-4 text-center">
                    &copy; 2023 - RB Aromas<br>
                </div>
                <div class="col-12 col-md-4 text-center text-md-right">

                </div>
            </div>
        </div>
        <footer>

            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
</body>

</html>